/**
 * This file contains all Data Transfer Object (DTO) and Command Model types
 * for the 10xCards API.
 *
 * DTOs (Data Transfer Objects) are types that define the shape of data
 * sent *from* the server *to* the client (responses).
 *
 * Command Models are types that define the shape of data
 * sent *from* the client *to* the server (requests).
 *
 * These types are derived from the auto-generated Supabase types
 * in './database.types.ts' to ensure consistency with the database schema.
 */

import { type Enums, type Tables, type TablesInsert, type TablesUpdate } from "./db/database.types";

// --- Base Entity Types ---
// Simplifies referencing the core database row/insert/update types.

/** Represents a row from the `flashcards` table. */
type FlashcardRow = Tables<"flashcards">;
/** Represents a row from the `generations` table. */
type GenerationRow = Tables<"generations">;
/** Represents the data required to insert a new `flashcards` row. */
type FlashcardInsert = TablesInsert<"flashcards">;
/** Represents the data required to insert a new `generations` row. */
type GenerationInsert = TablesInsert<"generations">;

// --- Enums ---

/**
 * Represents the source of a flashcard.
 * - `ai_full`: Generated by AI and accepted without edits.
 * - `ai_edited`: Generated by AI and edited before saving.
 * - `manual`: Created manually by the user.
 */
export type CardSource = Enums<"card_source">;

// --- Flashcard Resource ---

/**
 * **[DTO]**
 * The main object representing a flashcard returned to the client.
 * Omits the `user_id` for security/privacy.
 */
export type FlashcardDto = Omit<FlashcardRow, "user_id">;

/**
 * **[DTO]**
 * Pagination metadata included in paginated list responses.
 */
export interface PaginationDto {
  currentPage: number;
  totalPages: number;
  totalCount: number;
}

/**
 * **[DTO]**
 * The full response payload for `GET /flashcards`.
 */
export interface GetFlashcardsResponseDto {
  data: FlashcardDto[];
  pagination: PaginationDto;
}

/**
 * **[Command Model]**
 * Query parameters for the `GET /flashcards` endpoint.
 */
export interface GetFlashcardsQueryDto {
  page?: number;
  limit?: number;
  search?: string;
  /** Field to sort by. */
  sort?: "created_at" | "updated_at" | "front" | "back";
  /** Sort order. */
  order?: "asc" | "desc";
}

/**
 * **[Command Model]**
 * The structure of a single flashcard in the `POST /flashcards` request.
 * This type is used within the `CreateFlashcardsCommand`.
 */
export type CreateFlashcardDto = Pick<FlashcardInsert, "front" | "back" | "source" | "generation_id">;

/**
 * **[Command Model]**
 * The full request payload for `POST /flashcards`.
 * Used to create a batch of one or more flashcards.
 */
export interface CreateFlashcardsCommand {
  flashcards: CreateFlashcardDto[];
}

/**
 * **[DTO]**
 * The full response payload for `POST /flashcards`.
 */
export interface CreateFlashcardsResponseDto {
  flashcards: FlashcardDto[];
}

/**
 * **[Command Model]**
 * The request payload for `PATCH /flashcards/:id`.
 * Allows updating only the `front` and `back` fields.
 */
export type UpdateFlashcardCommand = Pick<TablesUpdate<"flashcards">, "front" | "back">;

// --- Generation Resource ---

/**
 * **[Command Model]**
 * The request payload for `POST /generations/generate-candidates`.
 */
export interface GenerateCandidatesCommand {
  /** The source text to generate flashcards from (1,000-10,000 chars). */
  source_text: string;
}

/**
 * **[DTO]**
 * The structure of a single, non-persistent flashcard candidate
 * returned by the `POST /generations/generate-candidates` endpoint.
 */
export type FlashcardCandidateDto = Pick<FlashcardRow, "front" | "back">;

/**
 * **[DTO]**
 * The metadata returned by the `POST /generations/generate-candidates` endpoint.
 */
export interface GenerationMetadataDto {
  /** The AI model identifier used for generation (e.g., "anthropic/claude-3-haiku"). */
  model_used: string | null;
  /** The time taken for the AI to respond, in milliseconds. */
  generation_duration_ms: number | null;
  /** The character length of the original `source_text`. */
  source_text_length: number;
  /** SHA-256 hash of the source text. */
  source_text_hash: string;
}

/**
 * **[DTO]**
 * The full response payload for `POST /generations/generate-candidates`.
 */
export interface GenerateCandidatesResponseDto {
  candidates: FlashcardCandidateDto[];
  metadata: GenerationMetadataDto;
}

/**
 * **[Command Model]**
 * The structure of the `generation_log` object within the
 * `POST /generations` request.
 */
export type CreateGenerationLogDto = Pick<
  GenerationInsert,
  | "model"
  | "generation_duration"
  | "source_text_hash"
  | "source_text_length"
  | "generated_count"
  | "accepted_unedited_count"
  | "accepted_edited_count"
  | "deleted_count"
>;

/**
 * **[Command Model]**
 * The full request payload for `POST /generations`.
 * This command logs the summary of a generation event.
 */
export interface CreateGenerationCommand {
  generation_log: CreateGenerationLogDto;
}

/**
 * **[DTO]**
 * The response payload for `POST /generations`.
 * Returns the newly created `generations` log entry.
 */
export type CreateGenerationResponseDto = Omit<GenerationRow, "user_id">;

// --- View Models ---

/**
 * View model for modal states.
 * Tracks which modal is open and associated data.
 */
export interface ModalState {
  editModal: {
    isOpen: boolean;
    flashcard: FlashcardDto | null;
  };
  deleteModal: {
    isOpen: boolean;
    flashcard: FlashcardDto | null;
  };
}
