-- migration: initial schema for 10xcards
-- purpose: create core tables (flashcards, generations), custom types, indexes, and rls policies
-- affected tables: flashcards, generations
-- special considerations: enables row level security for user data isolation

-- create custom enum type for tracking card source (ai vs manual creation)
create type public.card_source as enum (
  'ai_full',   -- generated by ai and accepted without edits
  'ai_edited', -- generated by ai and edited before saving
  'manual'     -- created using the manual add flow
);

-- create generations table to log ai generation events for metrics
create table public.generations (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model varchar(100),
  generation_duration integer check (generation_duration > 0),
  source_text_hash char(64),
  source_text_length integer not null check (source_text_length >= 1000 and source_text_length <= 10000),
  generated_count integer not null default 0 check (generated_count >= 0),
  accepted_unedited_count integer not null default 0 check (accepted_unedited_count >= 0),
  accepted_edited_count integer not null default 0 check (accepted_edited_count >= 0),
  deleted_count integer not null default 0 check (deleted_count >= 0),
  created_at timestamptz not null default now()
);

-- create flashcards table to store user's individual flashcards
create table public.flashcards (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  generation_id bigint references public.generations(id) on delete set null,
  front varchar(200) not null,
  back varchar(500) not null,
  source public.card_source not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- create indexes for performance on user_id columns (critical for rls)
create index flashcards_user_id_idx on public.flashcards (user_id);
create index generations_user_id_idx on public.generations (user_id);

-- create trigger function to automatically update updated_at timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- create trigger on flashcards table to auto-update updated_at column
create trigger on_flashcards_updated
  before update on public.flashcards
  for each row
  execute function public.handle_updated_at();

-- enable row level security on flashcards table
alter table public.flashcards enable row level security;

-- rls policy: users can read their own flashcards
create policy "enable read access for user's own flashcards"
  on public.flashcards
  for select
  using (auth.uid() = user_id);

-- rls policy: users can create flashcards for themselves
create policy "enable insert for own flashcards"
  on public.flashcards
  for insert
  with check (auth.uid() = user_id);

-- rls policy: users can update their own flashcards
create policy "enable update for user's own flashcards"
  on public.flashcards
  for update
  using (auth.uid() = user_id);

-- rls policy: users can delete their own flashcards
create policy "enable delete for user's own flashcards"
  on public.flashcards
  for delete
  using (auth.uid() = user_id);

-- enable row level security on generations table
alter table public.generations enable row level security;

-- rls policy: users can read their own generation logs
create policy "enable read access for user's own generation logs"
  on public.generations
  for select
  using (auth.uid() = user_id);

-- rls policy: users can create generation logs for themselves
create policy "enable insert for own generation logs"
  on public.generations
  for insert
  with check (auth.uid() = user_id);